name: Run golangci-lint

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1